print("\n")
print("***************")
print("* Ejercicio 2")
print("***************")

a = float(input("Precio primer artúculo: "))
b = float(input("Precio segundo artúculo: "))
c = float(input("Precio tercer artúculo: "))
saldo_inical = float(input("Saldo inicial: "))
saldo_final = saldo_inical - (a + b + c)
print("El saldo final de la tarjeta es:", saldo_final, "\n\n\n")
